# Generated by Django 3.1.7 on 2021-03-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Modelo', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Km', models.IntegerField()),
                ('Ciudad', models.CharField(max_length=100)),
                ('Transimisión', models.CharField(max_length=100)),
                ('Tipo_auto', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=10)),
                ('Combustible', models.CharField(max_length=100)),
                ('Pasajeros', models.IntegerField()),
                ('Estado', models.CharField(max_length=100)),
                ('Extras', models.CharField(max_length=1000)),
            ],
        ),
    ]
