# Generated by Django 3.1.7 on 2021-03-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210323_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Transimisión',
            new_name='Transimision',
        ),
    ]
